-- MySQL Script generated by MySQL Workbench
-- Mon Oct 24 11:32:11 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema PunchTheClock
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema PunchTheClock
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `PunchTheClock` DEFAULT CHARACTER SET utf8 ;
USE `PunchTheClock` ;

-- -----------------------------------------------------
-- Table `PunchTheClock`.`tipo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PunchTheClock`.`tipo` (
  `TipoID` INT NOT NULL AUTO_INCREMENT,
  `TipoNome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`TipoID`))
ENGINE = InnoDB;

INSERT INTO `PunchTheClock`.`tipo` VALUES (1, 'Funcionário');
INSERT INTO `PunchTheClock`.`tipo` VALUES (2, 'Administrador');

-- -----------------------------------------------------
-- Table `PunchTheClock`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PunchTheClock`.`funcionario` (
  `FuncID` INT NOT NULL AUTO_INCREMENT,
  `FuncNome` VARCHAR(60) NOT NULL,
  `FuncEmail` VARCHAR(60) NOT NULL,
  `FuncNiver` DATE NOT NULL,
  `TipoID` INT NOT NULL,
  PRIMARY KEY (`FuncID`),
  INDEX `FuncionarioXTipo_idx` (`TipoID` ASC),
  CONSTRAINT `FuncionarioXTipo`
    FOREIGN KEY (`TipoID`)
    REFERENCES `PunchTheClock`.`tipo` (`TipoID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `PunchTheClock`.`horarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `PunchTheClock`.`horarios` (
  `HorarioID` INT NOT NULL AUTO_INCREMENT,
  `FuncID` INT NOT NULL,
  `Data` DATETIME NOT NULL,
  `HorarioEntrada` DATETIME,
  `HorarioIIntervalo` DATETIME,
  `HorarioVIntervalo` DATETIME,
  `HorarioSaida` DATETIME,
  PRIMARY KEY (`HorarioID`),
  INDEX `HorarioXFuncionario_idx` (`FuncID` ASC),
  CONSTRAINT `HorarioXFuncionario`
    FOREIGN KEY (`FuncID`)
    REFERENCES `PunchTheClock`.`funcionario` (`FuncID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
